-- | Pure workflow binding and admission against the host's catalog snapshot.
module Max.Skill.Workflow (ResolvedWorkflow (..), bindWorkflowContracts, resolveWorkflow) where

import Control.Monad (unless)
import Data.Aeson (Value)
import Data.Foldable (traverse_)
import Data.List (nub)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import Max.Skill.Contract (validateValue)
import Max.Skill.Package
import Max.Tool.Bundles
import Max.Tool.Types

data ResolvedWorkflow = ResolvedWorkflow
  { rwWorkflow :: !Workflow,
    rwVersion :: !Text,
    rwCatalog :: ![CatalogTool]
  }
  deriving stock (Show, Eq)

-- Fingerprint the actual host definition, including effect and authority changes.
-- The schema hash is generated by the same catalog used by invocation admission.
fingerprint :: CatalogTool -> Text
fingerprint entry = skillLoadVersion (T.pack (show entry.ctDefinition) <> ":" <> entry.ctSchemaHash.unSchemaHash)

bindWorkflowContracts :: [CatalogTool] -> [SkillLoad] -> Either Text [SkillLoad]
bindWorkflowContracts catalog = traverse bind
  where
    available = Map.fromList [(t.ctDefinition.tdRef.unToolRef, t) | t <- catalog]
    bind load = case load.slPackage of
      Nothing -> Right load
      Just p -> do
        validatePackageName load.slName
        validatePackage p.ppContent
        let names = nub (concatMap (.wfTools) (Map.elems p.ppContent.spWorkflows))
        contracts <- traverse (\name -> maybe (Left ("workflow requires unavailable tool: " <> name)) (Right . (name,) . fingerprint) (Map.lookup name available)) names
        let pinned = load {slPackage = Just p {ppContracts = Map.fromList contracts}}
        Right pinned {slVersion = skillReceiptVersion pinned}

resolveWorkflow :: Map Text SkillLoad -> [CatalogTool] -> Text -> Value -> Either Text ResolvedWorkflow
resolveWorkflow loaded catalog reference args = do
  (name, entry) <- case T.splitOn "/" reference of
    [name, entry] | not (T.null name || T.null entry) -> Right (name, entry)
    _ -> Left "workflow reference must be skill/entry"
  load <- maybe (Left "workflow skill is not loaded") Right (Map.lookup name loaded)
  unless (load.slVersion == skillReceiptVersion load) (Left "invalid pinned workflow receipt")
  package <- maybe (Left "loaded skill has no workflow package") Right load.slPackage
  workflow <- maybe (Left "workflow entry does not exist in loaded version") Right (Map.lookup entry package.ppContent.spWorkflows)
  validateValue workflow.wfInput args
  let available = Map.fromList [(t.ctDefinition.tdRef.unToolRef, t) | t <- catalog]
  selected <- traverse (\tool -> maybe (Left ("workflow tool is no longer available: " <> tool)) Right (Map.lookup tool available)) workflow.wfTools
  traverse_ (\tool -> unless (Map.lookup tool.ctDefinition.tdRef.unToolRef package.ppContracts == Just (fingerprint tool)) (Left ("workflow tool contract changed: " <> tool.ctDefinition.tdRef.unToolRef))) selected
  pure (ResolvedWorkflow workflow load.slVersion selected)
